name: Run Selenium Tests with Allure

on:
  push:
    branches: [ main ]  # Only run on push to main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install allure-pytest

      # Step 4: Create folder for Allure results
      - name: Create Allure results folder
        run: mkdir -p Reports/allure-results

      # Step 5: Run tests
      - name: Run Pytest with Allure
        run: |
          pytest -v -s --reruns 3 --reruns-delay 5 -n 2 --alluredir=Reports/allure-results

      # Step 6: Upload Allure results as artifact
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: Reports/allure-results
